### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by eunaumtenhoid**

### CODE REVIEW

**Comment by lassik** [comment]
Thanks! :) I'll merge this in a couple days. I have to do some cleanup first since the current master branch has a migration bug that makes it unusable.

**Comment by eunaumtenhoid** [comment]
NP ^^

**Comment by lassik** [comment]
Sorry for taking longer than intended with this. I ended up making a lot of changes and released a new versoin 0.5.0. Unfortunately many new translation strings were added along the way, so I didn't merge your translation yet. Can you check https://github.com/lassik/phpbb-ext-telegramnotifications/tree/master/language/en to find all the latest strings and submit a translation that has all of them? Thanks a lot!

**Comment by eunaumtenhoid** [comment]
NP ^^

**Comment by eunaumtenhoid** [comment]
update here >> https://github.com/lassik/phpbb-ext-telegramnotifications/pull/2

**Comment by lassik** [comment]
I merged the updated translations from PR #2 so I'm closing this older PR. Thanks :)

**Pull request closed without merging**
